name: build & tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"

    steps:
      - uses: actions/checkout@v2

      - name: Lint and test
        run: make test

      - name: Build
        run: make build

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
